### ISSUE TITLE
Videos won't send

### ISSUE THREAD

**Issue by 1000goalgaming** [SocialXNetwork/socialx_react_native#157] opened 2018-12-15 23:43 UTC
**Describe the bug**
If I try to post a video with text, it restores me back to the feed as if it was uploaded... but it never is. It never shows up anywhere on the profile, feed, etc.

**To Reproduce**
1. Make a post
2. Put a video inside it

**Smartphone (please complete the following information):**
 - Device: LG K20 (VS501)
 - OS: Android 7.0
 - Version VS5011AA

![capture _2018-12-15-15-30-35 1](https://user-images.githubusercontent.com/31747246/50048403-ab418800-0090-11e9-800b-88de83bd8901.png)

**Comment by Shadyzpop** [comment] 2018-12-16 01:34
Duplicate of #155

**Comment by ChristBKK** [comment] 2018-12-19 14:37
from @1000goalgaming  also videos still won't send, comes up with 'Oops, an error occured' - would reproduce and write a new issue but it's too tedious for me rn :p

**Comment by alexcroitoru95** [comment] 2018-12-19 14:50
Just posed a video which contains text.

<img width="440" alt="screenshot 2018-12-19 at 16 48 36" src="https://user-images.githubusercontent.com/22367700/50227293-18655e00-03ae-11e9-88dd-56be8c9a5910.png">

**Comment by 1000goalgaming** [comment] 2018-12-19 23:38
Is there a size limit? The video I was trying to send was 4.03MB.

**Comment by Shadyzpop** [comment] 2018-12-19 23:44
hey, there isnt any size limit, there was a bug with the app that didnt allow android devices to send over videos, version 4.1+ should fix this issue

**Comment by ChristBKK** [comment] 2018-12-21 05:04
@1000goalgaming  can you test it again on version 4.1 ? highly appreciated

**Comment by Shadyzpop** [comment] 2019-01-03 13:23
@1000goalgaming can you please test this again?

**Closed** 2019-01-04 17:01 UTC
Labels: Waiting for Response, bug
