### ISSUE TITLE
Could not update the profile

### ISSUE THREAD

**Issue by sysulsb** [SocialXNetwork/socialx_react_native#173] opened 2019-01-01 06:35 UTC
when i try to edit my profile photo.it said:"Could not update the profile"

Smartphone

Device: huawei Honor V10
OS: Android 8.0.0
RAM: 6 GB
![23](https://user-images.githubusercontent.com/35393878/50570755-73e21380-0dd2-11e9-9864-5e1e51c8af34.jpg)
![24](https://user-images.githubusercontent.com/35393878/50570762-b146a100-0dd2-11e9-9366-07cc143850b3.jpg)

**Comment by alexcroitoru95** [comment] 2019-01-03 13:34
@Shadyzpop I can't reproduce this.

**Comment by Shadyzpop** [comment] 2019-01-03 13:37
Lets wait for the issue owner otherwise we close it in 7 days

**Comment by sysulsb** [comment] 2019-01-04 00:57
@alexsirbu04 @Shadyzpop @ChristBKK  how to help ? the problem still there

**Comment by alexcroitoru95** [comment] 2019-01-04 07:44
@sysulsb We will further test this. Thank you!

**Comment by sysulsb** [comment] 2019-01-08 11:10
@alexcroitoru95  hi,the problem still there. still can't update

**Comment by alexcroitoru95** [comment] 2019-01-09 09:20
@sysulsb Please enter at least 10 characters on the Bio Input. We will update the error so that the user will know about this. Also, please let us know if it works. Thx :)

**Comment by sysulsb** [comment] 2019-01-09 10:54
@alexcroitoru95 it is ok now.good work.  yes. it need some suggetion when it need 10 characters

**Comment by alexcroitoru95** [comment] 2019-01-09 10:55
@sysulsb Thank you for your suggestion! We are implementing this right now and should be available on the next release 👍

**Closed by alexcroitoru95** 2019-01-09 10:55 UTC
Labels: bug
